name: Sniff environment

on:
  push:
    branches:
      - master

jobs:
  sniff-linux:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              name: "Ubuntu latest",
              os: ubuntu-latest,
            }
          - {
              name: "Ubuntu 22.04",
              os: ubuntu-22.04,
            }
          - {
              name: "Ubuntu 20.04",
              os: ubuntu-20.04,
            }
    steps:
      - name: Check runner
        run: |
          uname --all
          lscpu
      - name: Check versions
        run: |
          clang --version
          clang++ --version
          cmake --version
          gcc --version
          g++ --version
          git --version

  sniff-macos:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              name: "macOS latest",
              os: macos-latest,
            }
          - {
              name: "macOS 12",
              os: macos-12,
            }
          - {
              name: "macOS 11",
              os: macos-11,
            }
    steps:
      - name: Check runner
        run: |
          uname
          lscpu
      - name: Check versions
        run: |
          clang --version
          clang++ --version
          cmake --version
          gcc --version
          g++ --version
          git --version
