name: Sniff environment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sniff-linux:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              name: "Ubuntu 24.04",
              os: ubuntu-24.04,
            }
          - {
              name: "Ubuntu 24.04 arm",
              os: ubuntu-24.04-arm,
            }
    steps:
      - name: Check runner
        run: |
          uname --all
          lscpu
      - name: Check versions
        run: |
          echo -e "\n######## clang version ########"
          clang --version
          echo -e "\n######## clang++ version ########"
          clang++ --version
          echo -e "\n######## cmake version ########"
          cmake --version
          echo -e "\n######## gcc version ########"
          gcc --version
          echo -e "\n######## g++ version ########"
          g++ --version
          echo -e "\n######## git version ########"
          git --version

  sniff-macos:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              name: "macOS 15",
              os: macos-15,
            }
          - {
              name: "macOS 13",
              os: macos-13,
            }
    steps:
      - name: Check runner
        run: |
          uname
          sysctl -a
      - name: Check versions
        run: |
          echo -e "\n######## clang version ########"
          clang --version
          echo -e "\n######## clang++ version ########"
          clang++ --version
          echo -e "\n######## cmake version ########"
          cmake --version
          echo -e "\n######## gcc version ########"
          gcc --version
          echo -e "\n######## g++ version ########"
          g++ --version
          echo -e "\n######## git version ########"
          git --version
