name: Sniff environment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sniff-linux:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              name: "Ubuntu 24.04",
              os: ubuntu-24.04,
            }
          - {
              name: "Ubuntu 22.04",
              os: ubuntu-22.04,
            }
          - {
              name: "Ubuntu 20.04",
              os: ubuntu-20.04,
            }
    steps:
      - name: Check runner
        run: |
          uname --all
          lscpu
      - name: Check versions
        run: |
          echo "######## clang version ########"
          clang --version
          echo "######## clang++ version ########"
          clang++ --version
          echo "######## cmake version ########"
          cmake --version
          echo "######## gcc version ########"
          gcc --version
          echo "######## g++ version ########"
          g++ --version
          echo "######## git version ########"
          git --version

  sniff-macos:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              name: "macOS latest",
              os: macos-latest,
            }
          - {
              name: "macOS 12",
              os: macos-12,
            }
          - {
              name: "macOS 11",
              os: macos-11,
            }
    steps:
      - name: Check runner
        run: |
          uname
          sysctl -a
      - name: Check versions
        run: |
          echo "######## clang version ########"
          clang --version
          echo "######## clang++ version ########"
          clang++ --version
          echo "######## cmake version ########"
          cmake --version
          echo "######## gcc version ########"
          gcc --version
          echo "######## g++ version ########"
          g++ --version
          echo "######## git version ########"
          git --version
